version: '3.8'

services:
  # PostgreSQL service
  postgres:
    image: postgres:16.3
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=go-social
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

# Volumes to persist PostgreSQL data
volumes:
  postgres_data:
    driver: local
