version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:9.2
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=go_social
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

# Volumes to persist MySQL data
volumes:
  mysql_data:
    driver: local
